DROP TABLE IF EXISTS `PRJM010001`;
CREATE TABLE `prjm010`.`PRJM010001` (
  `person_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dt_save` DATE,
  `situation` VARCHAR(10),
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PRJM010010`;
CREATE TABLE `prjm010`.`PRJM010010` (
  `person_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name_person` varchar(64) NOT NULL,
  `phonenumber` VARCHAR(10),
  `rg_person` VARCHAR(10) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`person_id`),
  KEY `FK_PRJM010010_PRJM010001_idx` (`person_id`),
  CONSTRAINT `fk_PRJM010010_PRJM010001` FOREIGN KEY (`person_id`) REFERENCES `PRJM010001` (`person_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PRJM010011`;
CREATE TABLE `prjm010`.`PRJM010011` (
  `classification_id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(64) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`classification_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PRJM010012`;
CREATE TABLE `prjm010`.`PRJM010012` (
  `classification_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`classification_id`, `person_id`),
  KEY `FK_PRJM010012_PRJM010001_idx` (`person_id`),
  KEY `FK_PRJM010012_PRJM010011_idx` (`classification_id`),
  CONSTRAINT `fk_PRJM010012_PRJM010001` FOREIGN KEY (`person_id`) REFERENCES `PRJM010001` (`person_id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRJM010012_PRJM010011` FOREIGN KEY (`classification_id`) REFERENCES `PRJM010011` (`classification_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PRJM010013`;
CREATE TABLE `prjm010`.`PRJM010013` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `person_id` int(11) NOT NULL,
  `login` varchar(64) NOT NULL,
  `password` varchar(256) NOT NULL,
  `inadmin` tinyint(1) NOT NULL DEFAULT 0,
  `dtregister` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`user_id`),
  KEY `FK_PRJM010013_PRJM010001_idx` (`person_id`),
  CONSTRAINT `fk_PRJM010013_PRJM010001` FOREIGN KEY (`person_id`) REFERENCES `PRJM010001` (`person_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PRJM010014`;
CREATE TABLE `prjm010`.`PRJM010014` (
  `visitant_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `daydate` DATE NOT NULL,
  `dayhour` TIME,
  `company` VARCHAR(100),
  `reason` VARCHAR(100),
  `badge` CHAR(3) NOT NULL,
  `auth` VARCHAR(45) NOT NULL,
  `sign` VARCHAR(100) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`visitant_id`),
  KEY `FK_PRJM010014_PRJM010001_idx` (`person_id`),
  KEY `FK_PRJM010014_PRJM010013_idx` (`user_id`),
  CONSTRAINT `fk_PRJM010014_PRJM010001` FOREIGN KEY (`person_id`) REFERENCES `PRJM010001` (`person_id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRJM010014_PRJM010013` FOREIGN KEY (`user_id`) REFERENCES `PRJM010013` (`user_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;